apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: mysql-resource-claim-cross-namespace
  namespace: service-instances
spec:
  consumingNamespaces:
    - '*'
  subject:
    group: with.sql.tanzu.vmware.com
    kind: MySQL